version: '3.8'

services:
  angular-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    depends_on:
      - mqtt-broker
      - api

  mqtt-broker:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mqtt.conf:/mosquitto/config/mosquitto.conf

  

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    environment:
      DB_USER: root
      DB_PASSWORD: password
      DB_NAME: calidad_aire
    ports:
      - "3000:3000"
    
